version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/build
    
permissions:
  - object: /home/ubuntu/build
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: scripts/after-deploy.sh
      timeout: 300
      runas: ubuntu